plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ashnapatch.xposed'
    compileSdk 34

    defaultConfig {
        applicationId 'com.ashnapatch.xposed'
        minSdk 24
        targetSdk 34
        versionCode 5
        versionName '1.4.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
